FROM python
ENV PYTHONPATH "${PYTHONPATH}:/src"

RUN pip install jupyter

RUN mkdir /src/
WORKDIR /src/

CMD pip install . && cd docs/docs/ && jupyter notebook --ip=0.0.0.0  --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
