FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt update --fix-missing
RUN apt install -y \
    curl \
    python3.6-dev \
    python3.7-dev \
    python3.8-dev \
    python3.9-dev \
    python3.10-dev \
    python3-pip
RUN pip3 install --upgrade pip

RUN pip3 install tox
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
ENV PATH "/root/.poetry/bin:$PATH"

RUN mkdir src
WORKDIR /src

CMD tox --parallel all
