name: Publish Documentation
on:
  push:
    branches:    
      - master

jobs:
  publish:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3
    - name: Install dependencies
      run: |
        poetry install
    - name: Publish package
      run: |
        cd docs/
        poetry run mkdocs gh-deploy --force
